### ISSUE TITLE
Deploy fails every other time

### ISSUE THREAD

**Issue by michaelchacko** [JacisNonsense/GradleRIO-C#1]
I'm having a slightly odd issue. When I deploy with `./gradlew build deploy`, it only successfully deploys every other time.. When it fails, it kills the "Robot Code" status on the driver station until I run `./gradlew build deploy` again.

Here is the error I get when it fails:
https://gist.github.com/chackotaco/5c54235e52234868fdff68c9b88770d2

Here is the output of  `./gradlew build deploy --debug`
https://gist.github.com/chackotaco/f1e12df02444a96ce99c4f2cf07ad9dd

Any help would be greatly appreciated
Thanks for making such a great tool!

**Comment by JaciBrunning** [comment]
Ahh, I believe this is because I forgot to migrate some changes from GradleRIO to GradleRIO-C (I believe this is mostly in netconsole). I'll have a fix up in a few hours

**Comment by michaelchacko** [comment]
Thanks for your help and timely response!

**Comment by JaciBrunning** [comment]
Give `2017.0.1` a try. This should kill netconsole before the deploy and allow the program to be deployed consistently.

**Comment by michaelchacko** [comment]
Will test tomorrow with our Rio. Thanks again

**Comment by michaelchacko** [comment]
Same issue unfortunately. Deploys every other time.

`./gradlew build deploy --debug` [fail output](https://gist.github.com/chackotaco/c2fbedba433d5da042c5c21b207cf1ba)

Not sure if it matters but I am using the barebones build.gradle configuration. The only thing i've changed is the team number.

**Comment by JaciBrunning** [comment]
Can you run again with `./gradlew build deploy --stacktrace`?

**Comment by michaelchacko** [comment]
Sure!

[Link to gist](https://gist.github.com/chackotaco/ede451e2984bff19efc3e65fe7d1c9e5)

**Comment by JaciBrunning** [comment]
@chackotaco give `2017.0.2` a shot. It more closely mimics WPILib's eclipse plugins

**Comment by michaelchacko** [comment]
Getting a different error with 2017.0.2
[Stacktrace](https://gist.github.com/chackotaco/22715fa164b773cc5f9f58ee2b9b2834)

EDIT:
Also I'm getting that error every time I try to deploy. Switching back to 2017.0.1 works every other time

**Comment by JaciBrunning** [comment]
That was my mistake. `2017.0.3` should resolve the new issue

**Comment by michaelchacko** [comment]
Getting another error every time
[Stacktrace](https://gist.github.com/chackotaco/3b46327c10ba7285ea9541b8af49561c)
Thanks again for the continued support

**Comment by JaciBrunning** [comment]
Give `2017.0.4` a crack.

**Comment by michaelchacko** [comment]
Getting another error every time with 2017.0.4
[Stacktrace](https://gist.github.com/chackotaco/789db8591383db37220e82c18068f0b6)

EDIT: Fixed link

**Comment by JaciBrunning** [comment]
Hmfh, seems `setcap` needs an admin session. I'll put in a third admin session after the deploy one to set that. Hold tight

**Comment by JaciBrunning** [comment]
`2017.0.5` should fix setcap's problem

**Comment by michaelchacko** [comment]
That fixed it for me! Thanks so much!

Just one other issue I was having that you may want to know about: 
using "latest-version" in build.gradle did not work for me:
`plugins {
    id "jaci.openrio.cpp.gradle.GradleRIO-C" version "latest-version"
}
`
to get it to work, I had to replace "latest-version" with the actual version number ("2017.0.x")

Thanks again!

**Comment by JaciBrunning** [comment]
@chackotaco that's mentioned in the README [here](https://github.com/Open-RIO/GradleRIO-C#custom-implementation). I use `latest-version` so that gradle will error and the user will replace it themselves. The reason for this is because it's too tedious to update quickstart and all examples each new release. Gradle also doesn't permit official plugins to use the `+` versioning system
